package ca.mcgill.ecse321.boardroom.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.*;

import ca.mcgill.ecse321.boardroom.dtos.EventCreationDto;
import ca.mcgill.ecse321.boardroom.dtos.EventResponseDto;
import ca.mcgill.ecse321.boardroom.model.Event;
import ca.mcgill.ecse321.boardroom.services.EventService;

@RestController
@RequestMapping("/events")  // Base path for event endpoints
public class EventController {

    @Autowired
    private EventService eventService;

    /**
     * Create a new event.
     *
     * @param eventToCreate The event details to create
     * @return The created event, including its autogenerated ID
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public EventResponseDto createEvent(@RequestBody EventCreationDto eventToCreate) {
        try {
            Event createdEvent = eventService.createEvent(eventToCreate);
            return new EventResponseDto(createdEvent);
        } catch (Exception e) {
            throw new RuntimeException("Event creation failed", e);
        }
    }

}
